image: mcr.microsoft.com/dotnet/sdk:6.0-windowsservercore-ltsc2019

stages:
  - build
  - test

before_script:
  - dotnet --version
    
build_model:
  stage: build
  tags: [windows]
  script: 
    - dotnet build Main
      
build_view:
  stage: build
  tags: [windows]
  script: 
    - dotnet build View
      
test_model:
  stage: test
  tags: [windows]
  script:
    - dotnet test Test
